title: Хомяк Любителя Systemd
description: "Домашняя страрица Любителя Systemd на jekyll"
author:
  name: "Любитель Systemd"
  email: "andrewbalkon@disroot.org"
  url: "https://lolifox.000webhostapp.com/im"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "systemdfan"
year : "2021"
